---
- name: Packages | Ensure apt cache is up to date
  apt: update_cache=yes cache_valid_time=3600

- name: Packages | Make sure your system is up-to-date
  apt: upgrade=safe state=latest

- name: Install Varnish cache server
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
   - varnish

