---
galaxy_info:
  author: Web Essentials
  description: Installs/Configures ansible settings
  company: Web Essentials
  license: MIT
  min_ansible_version: 1.6
  platforms:
    - name: Ubuntu
      versions:
        - raring
        - saucy
        - trusty
  categories:
    - system
dependencies: []
