---
- name: Install packages
  yum: pkg={{ item }} state=installed
  with_items: apache_packages

- name: Add HTTPD config and enabled modules
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
  notify:
   - restart {{ apache_daemon }}

- name: Create site-enabled folder
  file: path=/etc/httpd/site-enabled owner=root group=root mode=0644 state=directory

- include: ssl.yml
  when: apache_ssl_enabled
